"use client"

import "@/components/header/style.css"
import SignIn from "../signIn/sigin"
import Head from "next/head"
import { useEffect, useState } from "react"

function useScroll() {
    const [ scrollPosition, setScrollPosition ] = useState(0);

    useEffect(() => {
        if(typeof window !== 'undefined') {
            const handleScroll = () => {
                setScrollPosition(window.pageYOffset);
            };
    
            window.addEventListener('scroll', handleScroll);
            return() => {
                window.removeEventListener('scroll', handleScroll);
            }
        }
    },[]);

    return scrollPosition;
}

export default function Header_Login() {
    const scrollPosition = useScroll();
    const [style, setStyle] = useState({});

    useEffect(() => {
        const opacity = scrollPosition <= 300 ? 1 - Math.min(scrollPosition / 300, 1) : 0;
        // 画面の幅が960px以上の場合にのみ透明度を適用
        if (window.innerWidth >= 960) {
            setStyle({ opacity: opacity });
        }
    }, [scrollPosition]);

    
    return(
        <>
            <Head>
                <title>ミライ投票</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png" />
                <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png" />
                <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png" />
                <link rel="icon" href="/favicons/favicon.icon" />
                <link rel="manifest" href="/favicons/site.webmanifest" />
                <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5" />
                <meta name="msapplication-config" content="/favicons/browserconfig.xml" />
                <meta name="msapplication-TileColor" content="#da532c" />
                <meta name="theme-color" content="#ffffff" />
            </Head>
            <header style={style}>
                <nav className="headerNav">
                    <ul className="header">
                        <li>
                            <h1>
                                <picture>
                                    <img alt="ロゴ" src="/img/logo.svg"/>
                                </picture>
                            </h1>
                        </li>
                        <li className="signIn">
                            <SignIn/>
                        </li>
                    </ul>
                </nav>
            </header>
        </>
    )
}


