"use client"

import "@/components/header/style.css"
import SignIn from "../signIn/sigin"
import Head from "next/head"


export default function Header_Login() {


    return(
        <>
            <Head>
                <title>ミライ投票</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png" />
                <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png" />
                <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png" />
                <link rel="icon" href="/favicons/favicon.icon" />
                <link rel="manifest" href="/favicons/site.webmanifest" />
                <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5" />
                <meta name="msapplication-config" content="/favicons/browserconfig.xml" />
                <meta name="msapplication-TileColor" content="#da532c" />
                <meta name="theme-color" content="#ffffff" />
            </Head>
            <header>
                <nav className="headerNav">
                    <ul className="header">
                        <li>
                            <h1>
                                <picture>
                                    <img alt="ロゴ" src="/img/logo.svg"/>
                                </picture>
                            </h1>
                        </li>
                        <li className="signIn">
                            <SignIn/>
                        </li>
                    </ul>
                </nav>
            </header>
        </>
    )
}


